# SQL Practice

SQL practice using SQLite and Pandas, covering querying, filtering, aggregation, joins, subqueries, CTEs, and window functions.

In [34]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('sales.db')

In [35]:
# create dataset
data = {
    "customer": ["Alice", "Bob", "Charlie", "Diana", "Eve",
                 "Frank", "Grace", "Henry", "Ivy", "Jack"],
    "product": ["Laptop", "Phone", "Tablet", "Laptop", "Phone",
                "Monitor", "Tablet", "Laptop", "Phone", "Monitor"],
    "category": ["Electronics"] * 10,
    "quantity": [1, 2, 1, 2, 3, 1, 2, 1, 2, 1],
    "price": [800, 500, 300, 800, 500, 250, 300, 800, 500, 250],
    "region": ["East", "West", "North", "East", "South",
               "West", "North", "South", "East", "West"]
}

df = pd.DataFrame(data)

df

  customer  product     category  quantity  price region
0    Alice   Laptop  Electronics         1    800   East
1      Bob    Phone  Electronics         2    500   West
2  Charlie   Tablet  Electronics         1    300  North
3    Diana   Laptop  Electronics         2    800   East
4      Eve    Phone  Electronics         3    500  South
5    Frank  Monitor  Electronics         1    250   West
6    Grace   Tablet  Electronics         2    300  North
7    Henry   Laptop  Electronics         1    800  South
8      Ivy    Phone  Electronics         2    500   East
9     Jack  Monitor  Electronics         1    250   West

In [36]:
df.to_sql('sales',conn,if_exists='replace',index=False)

10

## SELECT

`SELECT` retrieves data from a table.

In [38]:
query = """
       SELECT *
       FROM sales ;
       """
pd.read_sql_query(query,conn)

  customer  product     category  quantity  price region
0    Alice   Laptop  Electronics         1    800   East
1      Bob    Phone  Electronics         2    500   West
2  Charlie   Tablet  Electronics         1    300  North
3    Diana   Laptop  Electronics         2    800   East
4      Eve    Phone  Electronics         3    500  South
5    Frank  Monitor  Electronics         1    250   West
6    Grace   Tablet  Electronics         2    300  North
7    Henry   Laptop  Electronics         1    800  South
8      Ivy    Phone  Electronics         2    500   East
9     Jack  Monitor  Electronics         1    250   West

## Selecting Columns

Specific columns can be selected instead of retrieving the entire table.

In [39]:
query = """
       Select customer,product,price
       from sales;
       """
pd.read_sql_query(query,conn)

  customer  product  price
0    Alice   Laptop    800
1      Bob    Phone    500
2  Charlie   Tablet    300
3    Diana   Laptop    800
4      Eve    Phone    500
5    Frank  Monitor    250
6    Grace   Tablet    300
7    Henry   Laptop    800
8      Ivy    Phone    500
9     Jack  Monitor    250

## DISTINCT

`DISTINCT` returns unique values and removes duplicates.

In [40]:
query = """
     SELECT DISTINCT product
     FROM sales;
     """
pd.read_sql_query(query,conn)

   product
0   Laptop
1    Phone
2   Tablet
3  Monitor

## WHERE

`WHERE` filters rows based on a condition.

In [41]:
query = """
    SELECT *
    FROM sales
    WHERE price > 500 ;
    """
pd.read_sql_query(query,conn)

  customer product     category  quantity  price region
0    Alice  Laptop  Electronics         1    800   East
1    Diana  Laptop  Electronics         2    800   East
2    Henry  Laptop  Electronics         1    800  South

## AND / OR

`AND` requires all conditions to be true.

`OR` requires at least one condition to be true.

In [42]:
query = """
      SELECT *
      FROM sales
      WHERE price > 300
      AND region ='East' ;
      """
pd.read_sql_query(query,conn)

  customer product     category  quantity  price region
0    Alice  Laptop  Electronics         1    800   East
1    Diana  Laptop  Electronics         2    800   East
2      Ivy   Phone  Electronics         2    500   East

In [43]:
# OR
query = """
SELECT *
FROM sales
WHERE region = 'East'
OR region = 'West';
"""

pd.read_sql_query(query, conn)

  customer  product     category  quantity  price region
0    Alice   Laptop  Electronics         1    800   East
1      Bob    Phone  Electronics         2    500   West
2    Diana   Laptop  Electronics         2    800   East
3    Frank  Monitor  Electronics         1    250   West
4      Ivy    Phone  Electronics         2    500   East
5     Jack  Monitor  Electronics         1    250   West

## IN

`IN` checks whether a value matches any value in a specified list.

In [44]:
query = """
       SELECT *
       FROM sales
       WHERE product IN ('Laptop','Phone') ;
       """
pd.read_sql_query(query,conn)

  customer product     category  quantity  price region
0    Alice  Laptop  Electronics         1    800   East
1      Bob   Phone  Electronics         2    500   West
2    Diana  Laptop  Electronics         2    800   East
3      Eve   Phone  Electronics         3    500  South
4    Henry  Laptop  Electronics         1    800  South
5      Ivy   Phone  Electronics         2    500   East

## BETWEEN

`BETWEEN` filters values within a specified range.

In [45]:
query = """
      SELECT *
      FROM sales
      WHERE price BETWEEN 300 AND 800;
      """

pd.read_sql_query(query, conn)

  customer product     category  quantity  price region
0    Alice  Laptop  Electronics         1    800   East
1      Bob   Phone  Electronics         2    500   West
2  Charlie  Tablet  Electronics         1    300  North
3    Diana  Laptop  Electronics         2    800   East
4      Eve   Phone  Electronics         3    500  South
5    Grace  Tablet  Electronics         2    300  North
6    Henry  Laptop  Electronics         1    800  South
7      Ivy   Phone  Electronics         2    500   East

## LIKE

`LIKE` searches for a specified pattern in text.

`%` represents zero or more characters.

In [46]:
query = """
      SELECT *
      FROM sales
      WHERE customer LIKE 'A%';
      """

pd.read_sql_query(query, conn)

  customer product     category  quantity  price region
0    Alice  Laptop  Electronics         1    800   East

In [47]:
query = """
      SELECT *
      FROM sales
      WHERE customer LIKE '%A';
      """

pd.read_sql_query(query, conn)

  customer product     category  quantity  price region
0    Diana  Laptop  Electronics         2    800   East

## ORDER BY

`ORDER BY` sorts query results.

`ASC` sorts in ascending order.

`DESC` sorts in descending order.

In [48]:
query = """
     SELECT *
     FROM sales
     ORDER BY price DESC;
     """

pd.read_sql_query(query, conn)

  customer  product     category  quantity  price region
0    Alice   Laptop  Electronics         1    800   East
1    Diana   Laptop  Electronics         2    800   East
2    Henry   Laptop  Electronics         1    800  South
3      Bob    Phone  Electronics         2    500   West
4      Eve    Phone  Electronics         3    500  South
5      Ivy    Phone  Electronics         2    500   East
6  Charlie   Tablet  Electronics         1    300  North
7    Grace   Tablet  Electronics         2    300  North
8    Frank  Monitor  Electronics         1    250   West
9     Jack  Monitor  Electronics         1    250   West

## LIMIT

`LIMIT` restricts the number of rows returned.

In [17]:
query = """
     SELECT *
     FROM sales
     ORDER BY price DESC
     LIMIT 5;
     """

pd.read_sql_query(query, conn)

  customer product     category  quantity  price region
0    Alice  Laptop  Electronics         1    800   East
1    Diana  Laptop  Electronics         2    800   East
2    Henry  Laptop  Electronics         1    800  South
3      Bob   Phone  Electronics         2    500   West
4      Eve   Phone  Electronics         3    500  South

## Aggregate Functions

Aggregate functions perform calculations on multiple rows.

Common aggregate functions include:

- `COUNT()`
- `SUM()`
- `AVG()`
- `MIN()`
- `MAX()`

In [18]:
query = """
    SELECT
    COUNT(*) AS total_sales,
    SUM(quantity) AS total_quantity,
    AVG(price) AS average_price,
    MIN(price) AS minimum_price,
    MAX(price) AS maximum_price
    FROM sales;
    """

pd.read_sql_query(query, conn)

   total_sales  total_quantity  average_price  minimum_price  maximum_price
0           10              16          500.0            250            800

## GROUP BY

`GROUP BY` groups rows that have the same value in one or more columns.

It is commonly used with aggregate functions.

In [19]:
query = """
SELECT
    product,
    SUM(quantity) AS total_quantity
FROM sales
GROUP BY product;
"""

pd.read_sql_query(query, conn)

   product  total_quantity
0   Laptop               4
1  Monitor               2
2    Phone               7
3   Tablet               3

In [20]:
query = """
SELECT
    region,
    product,
    SUM(quantity) AS total_quantity
FROM sales
GROUP BY region, product;
"""

pd.read_sql_query(query, conn)

  region  product  total_quantity
0   East   Laptop               3
1   East    Phone               2
2  North   Tablet               3
3  South   Laptop               1
4  South    Phone               3
5   West  Monitor               2
6   West    Phone               2

## HAVING

`HAVING` filters grouped results.

`WHERE` filters rows before grouping, while `HAVING` filters groups after aggregation.

In [21]:
query = """
SELECT
    product,
    SUM(quantity) AS total_quantity
FROM sales
GROUP BY product
HAVING SUM(quantity) > 2;
"""

pd.read_sql_query(query, conn)

  product  total_quantity
0  Laptop               4
1   Phone               7
2  Tablet               3

## CASE

`CASE` allows conditional logic inside a SQL query.

It works similarly to an `if / elif / else` structure.

In [22]:
query = """
SELECT
    customer,
    product,
    price,
    CASE
        WHEN price >= 700 THEN 'High'
        WHEN price >= 400 THEN 'Medium'
        ELSE 'Low'
    END AS price_category
FROM sales;
"""

pd.read_sql_query(query, conn)

  customer  product  price price_category
0    Alice   Laptop    800           High
1      Bob    Phone    500         Medium
2  Charlie   Tablet    300            Low
3    Diana   Laptop    800           High
4      Eve    Phone    500         Medium
5    Frank  Monitor    250            Low
6    Grace   Tablet    300            Low
7    Henry   Laptop    800           High
8      Ivy    Phone    500         Medium
9     Jack  Monitor    250            Low

## Calculated Columns

SQL can create new values from existing columns.

In [23]:
query = """
SELECT
    customer,
    product,
    quantity,
    price,
    quantity * price AS total_sales
FROM sales;
"""

pd.read_sql_query(query, conn)

  customer  product  quantity  price  total_sales
0    Alice   Laptop         1    800          800
1      Bob    Phone         2    500         1000
2  Charlie   Tablet         1    300          300
3    Diana   Laptop         2    800         1600
4      Eve    Phone         3    500         1500
5    Frank  Monitor         1    250          250
6    Grace   Tablet         2    300          600
7    Henry   Laptop         1    800          800
8      Ivy    Phone         2    500         1000
9     Jack  Monitor         1    250          250

In [24]:
customers = pd.DataFrame({
    "customer": ["Alice", "Bob", "Charlie", "Diana", "Eve",
                 "Frank", "Grace", "Henry", "Ivy", "Jack"],
    "age": [25, 32, 28, 41, 35, 29, 38, 45, 27, 33],
    "membership": ["Gold", "Silver", "Gold", "Gold", "Silver",
                   "Bronze", "Gold", "Silver", "Bronze", "Gold"]
})

customers.to_sql("customers", conn, if_exists="replace", index=False)

customers

  customer  age membership
0    Alice   25       Gold
1      Bob   32     Silver
2  Charlie   28       Gold
3    Diana   41       Gold
4      Eve   35     Silver
5    Frank   29     Bronze
6    Grace   38       Gold
7    Henry   45     Silver
8      Ivy   27     Bronze
9     Jack   33       Gold

## INNER JOIN

An `INNER JOIN` returns rows where there is a matching value in both tables.

In [25]:
query = """
SELECT
    sales.customer,
    sales.product,
    sales.price,
    customers.membership
FROM sales
INNER JOIN customers
ON sales.customer = customers.customer;
"""

pd.read_sql_query(query, conn)

  customer  product  price membership
0    Alice   Laptop    800       Gold
1      Bob    Phone    500     Silver
2  Charlie   Tablet    300       Gold
3    Diana   Laptop    800       Gold
4      Eve    Phone    500     Silver
5    Frank  Monitor    250     Bronze
6    Grace   Tablet    300       Gold
7    Henry   Laptop    800     Silver
8      Ivy    Phone    500     Bronze
9     Jack  Monitor    250       Gold

## LEFT JOIN

A `LEFT JOIN` returns all rows from the left table and matching rows from the right table.

If there is no match, the right-side columns contain `NULL`.

In [26]:
query = """
SELECT
    sales.customer,
    sales.product,
    customers.membership
FROM sales
LEFT JOIN customers
ON sales.customer = customers.customer;
"""

pd.read_sql_query(query, conn)

  customer  product membership
0    Alice   Laptop       Gold
1      Bob    Phone     Silver
2  Charlie   Tablet       Gold
3    Diana   Laptop       Gold
4      Eve    Phone     Silver
5    Frank  Monitor     Bronze
6    Grace   Tablet       Gold
7    Henry   Laptop     Silver
8      Ivy    Phone     Bronze
9     Jack  Monitor       Gold

## RIGHT JOIN

A `RIGHT JOIN` returns all rows from the right table and matching rows from the left table.

In [49]:
query = """
SELECT
    customers.customer,
    customers.membership,
    sales.product
FROM sales
RIGHT JOIN customers
ON sales.customer = customers.customer;
"""

pd.read_sql_query(query, conn)

  customer membership  product
0    Alice       Gold   Laptop
1      Bob     Silver    Phone
2  Charlie       Gold   Tablet
3    Diana       Gold   Laptop
4      Eve     Silver    Phone
5    Frank     Bronze  Monitor
6    Grace       Gold   Tablet
7    Henry     Silver   Laptop
8      Ivy     Bronze    Phone
9     Jack       Gold  Monitor

## FULL OUTER JOIN

A `FULL OUTER JOIN` returns all rows from both tables, matching rows where possible.

In [50]:
query = """
SELECT
    customers.customer,
    customers.membership,
    sales.product
FROM sales
FULL OUTER JOIN customers
ON sales.customer = customers.customer;
"""

pd.read_sql_query(query, conn)

  customer membership  product
0    Alice       Gold   Laptop
1      Bob     Silver    Phone
2  Charlie       Gold   Tablet
3    Diana       Gold   Laptop
4      Eve     Silver    Phone
5    Frank     Bronze  Monitor
6    Grace       Gold   Tablet
7    Henry     Silver   Laptop
8      Ivy     Bronze    Phone
9     Jack       Gold  Monitor

## CROSS JOIN

A `CROSS JOIN` returns every possible combination of rows from two tables.

In [51]:
query = """
SELECT
    sales.product,
    customers.membership
FROM sales
CROSS JOIN customers;
"""

pd.read_sql_query(query, conn)

    product membership
0    Laptop       Gold
1    Laptop     Silver
2    Laptop       Gold
3    Laptop       Gold
4    Laptop     Silver
..      ...        ...
95  Monitor     Bronze
96  Monitor       Gold
97  Monitor     Silver
98  Monitor     Bronze
99  Monitor       Gold

[100 rows x 2 columns]

In [52]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4],
    "employee_name": ["Alice", "Bob", "Charlie", "Diana"],
    "manager_id": [None, 1, 1, 2]
})

employees.to_sql("employees", conn, if_exists="replace", index=False)

4

## SELF JOIN

A self join joins a table with itself.

It can be useful for relationships such as employees and their managers.

In [53]:
query = """
SELECT
    e.employee_name AS employee,
    m.employee_name AS manager
FROM employees e
LEFT JOIN employees m
ON e.manager_id = m.employee_id;
"""

pd.read_sql_query(query, conn)

  employee manager
0    Alice    None
1      Bob   Alice
2  Charlie   Alice
3    Diana     Bob

## Subquery

A subquery is a query nested inside another query.

It can be used when the result of one query is needed by another query.

In [27]:
query = """
SELECT *
FROM sales
WHERE price > (
    SELECT AVG(price)
    FROM sales
);
"""

pd.read_sql_query(query, conn)

  customer product     category  quantity  price region
0    Alice  Laptop  Electronics         1    800   East
1    Diana  Laptop  Electronics         2    800   East
2    Henry  Laptop  Electronics         1    800  South

## Common Table Expression

A CTE temporarily stores the result of a query using `WITH`.

CTEs can make complex queries easier to read and organize.

In [28]:
query = """
WITH product_sales AS (
    SELECT
        product,
        SUM(quantity * price) AS total_sales
    FROM sales
    GROUP BY product
)

SELECT *
FROM product_sales
WHERE total_sales > 1000;
"""

pd.read_sql_query(query, conn)

  product  total_sales
0  Laptop         3200
1   Phone         3500

## Window Functions

Window functions perform calculations across related rows without collapsing them into groups.

They are useful for rankings, running totals, comparisons, and other analytical calculations.

In [29]:
query = """
SELECT
    customer,
    product,
    price,
    RANK() OVER (ORDER BY price DESC) AS price_rank
FROM sales;
"""

pd.read_sql_query(query, conn)

  customer  product  price  price_rank
0    Alice   Laptop    800           1
1    Diana   Laptop    800           1
2    Henry   Laptop    800           1
3      Bob    Phone    500           4
4      Eve    Phone    500           4
5      Ivy    Phone    500           4
6  Charlie   Tablet    300           7
7    Grace   Tablet    300           7
8    Frank  Monitor    250           9
9     Jack  Monitor    250           9

## PARTITION BY

`PARTITION BY` divides rows into groups before a window function is applied.

This allows calculations such as ranking within each category.

In [30]:
query = """
SELECT
    region,
    customer,
    price,
    RANK() OVER (
        PARTITION BY region
        ORDER BY price DESC
    ) AS regional_rank
FROM sales;
"""

pd.read_sql_query(query, conn)

  region customer  price  regional_rank
0   East    Alice    800              1
1   East    Diana    800              1
2   East      Ivy    500              3
3  North  Charlie    300              1
4  North    Grace    300              1
5  South    Henry    800              1
6  South      Eve    500              2
7   West      Bob    500              1
8   West    Frank    250              2
9   West     Jack    250              2

# Mini Analysis

Using the sales dataset, we can identify total revenue by product and determine which products generate the most sales.

In [31]:
query = """
SELECT
    product,
    SUM(quantity) AS units_sold,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
ORDER BY revenue DESC;
"""

pd.read_sql_query(query, conn)

   product  units_sold  revenue
0    Phone           7     3500
1   Laptop           4     3200
2   Tablet           3      900
3  Monitor           2      500

## NULL Handling

`NULL` represents a missing or unknown value.

Common SQL tools for handling NULL values include:
- `IS NULL`
- `IS NOT NULL`
- `COALESCE()`
- `NULLIF()`

In [54]:
query = """
SELECT *
FROM customers
WHERE membership IS NULL;
"""

pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [customer, age, membership]
Index: []

In [55]:
query = """
SELECT
    customer,
    COALESCE(membership, 'Unknown') AS membership
FROM customers;
"""

pd.read_sql_query(query, conn)

  customer membership
0    Alice       Gold
1      Bob     Silver
2  Charlie       Gold
3    Diana       Gold
4      Eve     Silver
5    Frank     Bronze
6    Grace       Gold
7    Henry     Silver
8      Ivy     Bronze
9     Jack       Gold

## UNION

`UNION` combines the results of two queries and removes duplicate rows.

In [56]:
query = """
SELECT customer
FROM sales
WHERE region = 'East'

UNION

SELECT customer
FROM sales
WHERE region = 'West';
"""

pd.read_sql_query(query, conn)

  customer
0    Alice
1      Bob
2    Diana
3    Frank
4      Ivy
5     Jack

## UNION ALL

`UNION ALL` combines query results while keeping duplicates.

It is generally faster than `UNION` because duplicate removal is not performed.

In [57]:
query = """
SELECT customer
FROM sales
WHERE region = 'East'

UNION ALL

SELECT customer
FROM sales
WHERE region = 'West';
"""

pd.read_sql_query(query, conn)

  customer
0    Alice
1    Diana
2      Ivy
3      Bob
4    Frank
5     Jack

## String Functions

SQL provides functions for manipulating text data.

Examples include:
- `UPPER()`
- `LOWER()`
- `LENGTH()`
- `SUBSTR()`

In [58]:
query = """
SELECT
    customer,
    UPPER(customer) AS uppercase_name,
    LOWER(customer) AS lowercase_name,
    LENGTH(customer) AS name_length
FROM sales;
"""

pd.read_sql_query(query, conn)

  customer uppercase_name lowercase_name  name_length
0    Alice          ALICE          alice            5
1      Bob            BOB            bob            3
2  Charlie        CHARLIE        charlie            7
3    Diana          DIANA          diana            5
4      Eve            EVE            eve            3
5    Frank          FRANK          frank            5
6    Grace          GRACE          grace            5
7    Henry          HENRY          henry            5
8      Ivy            IVY            ivy            3
9     Jack           JACK           jack            4

In [59]:
df["sale_date"] = [
    "2026-01-15",
    "2026-01-20",
    "2026-02-05",
    "2026-02-12",
    "2026-02-25",
    "2026-03-03",
    "2026-03-15",
    "2026-03-22",
    "2026-04-10",
    "2026-04-18"
]

df.to_sql("sales", conn, if_exists="replace", index=False)

10

## Date Functions

SQL can extract and manipulate information from date values.

In [60]:
query = """
SELECT
    customer,
    sale_date,
    strftime('%Y', sale_date) AS year,
    strftime('%m', sale_date) AS month
FROM sales;
"""

pd.read_sql_query(query, conn)

  customer   sale_date  year month
0    Alice  2026-01-15  2026    01
1      Bob  2026-01-20  2026    01
2  Charlie  2026-02-05  2026    02
3    Diana  2026-02-12  2026    02
4      Eve  2026-02-25  2026    02
5    Frank  2026-03-03  2026    03
6    Grace  2026-03-15  2026    03
7    Henry  2026-03-22  2026    03
8      Ivy  2026-04-10  2026    04
9     Jack  2026-04-18  2026    04

## CAST

`CAST()` converts a value from one data type to another.

In [61]:
query = """
SELECT
    customer,
    CAST(price AS REAL) AS price
FROM sales;
"""

pd.read_sql_query(query, conn)

  customer  price
0    Alice  800.0
1      Bob  500.0
2  Charlie  300.0
3    Diana  800.0
4      Eve  500.0
5    Frank  250.0
6    Grace  300.0
7    Henry  800.0
8      Ivy  500.0
9     Jack  250.0

## ROW_NUMBER()

`ROW_NUMBER()` assigns a unique sequential number to each row within a window.

In [62]:
query = """
SELECT
    customer,
    product,
    price,
    ROW_NUMBER() OVER (
        ORDER BY price DESC
    ) AS row_number
FROM sales;
"""

pd.read_sql_query(query, conn)

  customer  product  price  row_number
0    Alice   Laptop    800           1
1    Diana   Laptop    800           2
2    Henry   Laptop    800           3
3      Bob    Phone    500           4
4      Eve    Phone    500           5
5      Ivy    Phone    500           6
6  Charlie   Tablet    300           7
7    Grace   Tablet    300           8
8    Frank  Monitor    250           9
9     Jack  Monitor    250          10

## LAG()

`LAG()` accesses a value from a previous row.

It is useful for comparing the current row with a previous value.

In [63]:
query = """
SELECT
    sale_date,
    price,
    LAG(price) OVER (
        ORDER BY sale_date
    ) AS previous_price
FROM sales;
"""

pd.read_sql_query(query, conn)

    sale_date  price  previous_price
0  2026-01-15    800             NaN
1  2026-01-20    500           800.0
2  2026-02-05    300           500.0
3  2026-02-12    800           300.0
4  2026-02-25    500           800.0
5  2026-03-03    250           500.0
6  2026-03-15    300           250.0
7  2026-03-22    800           300.0
8  2026-04-10    500           800.0
9  2026-04-18    250           500.0

## LEAD()

`LEAD()` accesses a value from a following row.

It is useful for comparing the current row with a future value.

In [64]:
query = """
SELECT
    sale_date,
    price,
    LEAD(price) OVER (
        ORDER BY sale_date
    ) AS next_price
FROM sales;
"""

pd.read_sql_query(query, conn)

    sale_date  price  next_price
0  2026-01-15    800       500.0
1  2026-01-20    500       300.0
2  2026-02-05    300       800.0
3  2026-02-12    800       500.0
4  2026-02-25    500       250.0
5  2026-03-03    250       300.0
6  2026-03-15    300       800.0
7  2026-03-22    800       500.0
8  2026-04-10    500       250.0
9  2026-04-18    250         NaN

## Running Total

Window functions can be used to calculate cumulative values across ordered rows.

In [65]:
query = """
SELECT
    sale_date,
    quantity,
    SUM(quantity) OVER (
        ORDER BY sale_date
    ) AS running_quantity
FROM sales;
"""

pd.read_sql_query(query, conn)

    sale_date  quantity  running_quantity
0  2026-01-15         1                 1
1  2026-01-20         2                 3
2  2026-02-05         1                 4
3  2026-02-12         2                 6
4  2026-02-25         3                 9
5  2026-03-03         1                10
6  2026-03-15         2                12
7  2026-03-22         1                13
8  2026-04-10         2                15
9  2026-04-18         1                16

## Conditional Aggregation

Conditional aggregation combines aggregate functions with `CASE` to calculate values based on conditions.

In [66]:
query = """
SELECT
    region,
    SUM(
        CASE
            WHEN price >= 500 THEN quantity
            ELSE 0
        END
    ) AS high_value_units
FROM sales
GROUP BY region;
"""

pd.read_sql_query(query, conn)

  region  high_value_units
0   East                 5
1  North                 0
2  South                 4
3   West                 2

In [32]:
conn.close()